name: CI to Docker Hub
on:
  push:
    tags:
      - "v*.*.*"
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: alvinso01/minecraft-server-1.12.2:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
